apiVersion: v1
kind: Service
metadata:
  name: hello-world-80-yktckrlupsqm-service
  labels:
    cloud.sealos.io/app-deploy-manager: hello-world
spec:
  ports:
    - port: 80
      targetPort: 80
      name: ulzhfcpltnca
      protocol: TCP
  selector:
    app: hello-world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  annotations:
    originImageName: nginx
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
    deploy.cloud.sealos.io/resize: 0Gi
  labels:
    app: hello-world
    cloud.sealos.io/app-deploy-manager: hello-world
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: hello-world
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-world
        restartTime: '20251203151456'
    spec:
      automountServiceAccountToken: false
      containers:
        - name: hello-world
          image: nginx
          env: []
          resources:
            requests:
              cpu: 20m
              memory: 51Mi
            limits:
              cpu: 200m
              memory: 512Mi
          ports:
            - containerPort: 80
              name: ulzhfcpltnca
          imagePullPolicy: Always
          volumeMounts: []
      volumes: []
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-80-zgzmibfjagut-network
  labels:
    cloud.sealos.io/app-deploy-manager: hello-world
    cloud.sealos.io/app-deploy-manager-domain: ebjmourctqie
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
spec:
  rules:
    - host: ebjmourctqie.sealoshzh.site
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: hello-world-80-yktckrlupsqm-service
                port:
                  number: 80
  tls:
    - hosts:
        - ebjmourctqie.sealoshzh.site
      secretName: wildcard-cert
