apiVersion: v1
kind: Service
metadata:
  name: hello-world-rzzdmyxaxgxj
  labels:
    cloud.sealos.io/app-deploy-manager: hello-world
spec:
  ports:
    - port: 80
      targetPort: 80
      name: ifwndjuyiyvv
      protocol: TCP
  selector:
    app: hello-world
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hello-world
  annotations:
    originImageName: nginx
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
    deploy.cloud.sealos.io/resize: 1Gi
  labels:
    app: hello-world
    cloud.sealos.io/app-deploy-manager: hello-world
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: hello-world
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  minReadySeconds: 10
  serviceName: hello-world-rzzdmyxaxgxj
  template:
    metadata:
      labels:
        app: hello-world
        restartTime: '20251203150639'
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 10
      containers:
        - name: hello-world
          image: nginx
          env: []
          resources:
            requests:
              cpu: 20m
              memory: 25Mi
            limits:
              cpu: 200m
              memory: 256Mi
          ports:
            - containerPort: 80
              name: ifwndjuyiyvv
          imagePullPolicy: Always
          volumeMounts:
            - name: vn-data
              mountPath: /data
      volumes: []
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /data
          value: '1'
        name: vn-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: network-xrgzlpxzraht
  labels:
    cloud.sealos.io/app-deploy-manager: hello-world
    cloud.sealos.io/app-deploy-manager-domain: blzpdakvvnua
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
spec:
  rules:
    - host: blzpdakvvnua.sealoshzh.site
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: hello-world-rzzdmyxaxgxj
                port:
                  number: 80
  tls:
    - hosts:
        - blzpdakvvnua.sealoshzh.site
      secretName: wildcard-cert
